print ("H       H"" M       M")
print ("H       H"" M       M")
print ("H       H"" M M   M M")
print ("H H H H H"" M M   M M")
print ("H       H"" M   M   M")
print ("H       H"" M       M")
print ("H       H"" M       M")
